added property to show inactive titles
pedromassango/bottom_navy_bar pull request #114
Opened 2024-03-30 07:21 UTC by agam1092005

Issue #68  resolved
Added new feature: Added property to show inactive titles using MediaQuery width properties to fit all the titles in the screen/display size

Updated readme file for docs
Signed-off-by: Agampreet Singh <agam1092005@gmail.com>

2024-03-30 11:04 UTC, antonio-pedro99 requested changes
@agam1092005 thanks for the PR. 
Can you add these changes to the CHANGELOG.md file?

2024-03-30 12:08 UTC, antonio-pedro99 commented on CHANGELOG.md
@agam1092005 can you add under version 7.0.0? That's the next version.

2024-03-30 12:13 UTC, agam1092005 commented on CHANGELOG.md
Done 👍🏻

2024-07-10 22:37 UTC, antonio-pedro99 approved these changes
LGMT
@agam1092005 thanks!

2024-07-10 22:37 UTC, merged